# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADMM_ENrun <- function(tildelogY, X, D_pos, D_vert_1, D_vert_neg1, tildedelta, rho, eta, tau, lambda, alpha, w, Gamma, Beta, Theta, max_iter, tol_abs, tol_rel, gamma, euc_tildelogY) {
    .Call(`_penAFT_ADMM_ENrun`, tildelogY, X, D_pos, D_vert_1, D_vert_neg1, tildedelta, rho, eta, tau, lambda, alpha, w, Gamma, Beta, Theta, max_iter, tol_abs, tol_rel, gamma, euc_tildelogY)
}

ADMM_SGrun <- function(tildelogY, X, D_pos, D_vert_1, D_vert_neg1, tildedelta, rho, eta, tau, lambda, alpha, w, v, borderIndexes, Gamma, Beta, Theta, max_iter, tol_abs, tol_rel, gamma, euc_tildelogY, n, l, p, G) {
    .Call(`_penAFT_ADMM_SGrun`, tildelogY, X, D_pos, D_vert_1, D_vert_neg1, tildedelta, rho, eta, tau, lambda, alpha, w, v, borderIndexes, Gamma, Beta, Theta, max_iter, tol_abs, tol_rel, gamma, euc_tildelogY, n, l, p, G)
}

